### ISSUE TITLE
[urgent] Problème correction

### ISSUE THREAD

**Issue by marcgg** [Utopiad/twitter-rpg#81]
Bonjour à tous,

Les accès que vous m'avez donnés dans le rapport ne fonctionnent pas, et je ne peux pas créer un premier scénario... je vois plein de choses intéressantes dans le rapport et le code mais la tel quel le site n'est pas opérationnel.

Pourriez vous très rapidement rétablir l'accès au compte mentionné dans le rapport (martinziserman@gmail.com) ?

Quand cela sera fait, prévenez moi immédiatement **par email**.

Merci et bon début d'année à vous tous !

--------

cc @Utopiad @Mziserman @Hemric @clovis-maniguet @Arnaud-Lustrat

**Comment by Utopiad** [comment]
Bonjour à vous,

nous avons fait le nécessaire, vous devriez maintenant pouvoir créer un monde sans problème. :)

Je vous ai envoyé un mail comme vous l'avez demandé, à l'adresse que j'ai trouvé sur votre page Github.

Bonne année 2017 !
